In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

d=DataFrame(np.random.uniform(size=100).reshape(25,4))

d

           0         1         2         3
0   0.256140  0.021821  0.861509  0.959911
1   0.122057  0.845226  0.696506  0.148699
2   0.726453  0.218114  0.960755  0.198306
3   0.906006  0.350190  0.126388  0.678321
4   0.905958  0.333877  0.745048  0.767306
5   0.740672  0.245764  0.122640  0.705787
6   0.248635  0.183440  0.634363  0.283858
7   0.284415  0.429537  0.383899  0.206239
8   0.768713  0.760318  0.970650  0.321685
9   0.454392  0.212103  0.256736  0.170178
10  0.398442  0.394336  0.797771  0.388758
11  0.928001  0.124364  0.975937  0.088078
12  0.248954  0.932197  0.245250  0.600394
13  0.633827  0.527758  0.400908  0.174506
14  0.898123  0.981077  0.385086  0.117124
15  0.363135  0.957774  0.103713  0.536464
16  0.156722  0.652997  0.947282  0.805937
17  0.237748  0.034058  0.450044  0.113343
18  0.743524  0.490304  0.833266  0.439628
19  0.719932  0.795728  0.491034  0.356091
20  0.943673  0.872107  0.491260  0.840621
21  0.143653  0.628237  0.222645  0.388624
22  0.067217  0.714923  0.171014  0.317878
23  0.971530  0.416940  0.511548  0.683686
24  0.591342  0.783401  0.284444  0.975851

In [5]:
cat_list=['first','second','third','fourth']

d['cat']=np.random.choice(cat_list,size=len(d))

d.sort('cat')

C:\Users\marvinw\AppData\Local\Continuum\Anaconda\lib\site-packages\ipykernel\__main__.py:5: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

           0         1         2         3     cat
0   0.256140  0.021821  0.861509  0.959911   first
18  0.743524  0.490304  0.833266  0.439628   first
17  0.237748  0.034058  0.450044  0.113343   first
14  0.898123  0.981077  0.385086  0.117124   first
11  0.928001  0.124364  0.975937  0.088078   first
6   0.248635  0.183440  0.634363  0.283858   first
10  0.398442  0.394336  0.797771  0.388758  fourth
24  0.591342  0.783401  0.284444  0.975851  fourth
5   0.740672  0.245764  0.122640  0.705787  fourth
16  0.156722  0.652997  0.947282  0.805937  second
9   0.454392  0.212103  0.256736  0.170178  second
4   0.905958  0.333877  0.745048  0.767306  second
20  0.943673  0.872107  0.491260  0.840621  second
15  0.363135  0.957774  0.103713  0.536464  second
7   0.284415  0.429537  0.383899  0.206239  second
19  0.719932  0.795728  0.491034  0.356091  second
1   0.122057  0.845226  0.696506  0.148699  second
22  0.067217  0.714923  0.171014  0.317878   third
21  0.143653  0.628237  0.222645  0.388624   third
8   0.768713  0.760318  0.970650  0.321685   third
3   0.906006  0.350190  0.126388  0.678321   third
13  0.633827  0.527758  0.400908  0.174506   third
23  0.971530  0.416940  0.511548  0.683686   third
2   0.726453  0.218114  0.960755  0.198306   third
12  0.248954  0.932197  0.245250  0.600394   third

In [6]:
d['cat_sort']=pd.Categorical(d['cat'],
                            categories=cat_list,
                            ordered=True)

d.sort('cat_sort')

C:\Users\marvinw\AppData\Local\Continuum\Anaconda\lib\site-packages\ipykernel\__main__.py:5: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

           0         1         2         3     cat cat_sort
0   0.256140  0.021821  0.861509  0.959911   first    first
6   0.248635  0.183440  0.634363  0.283858   first    first
18  0.743524  0.490304  0.833266  0.439628   first    first
11  0.928001  0.124364  0.975937  0.088078   first    first
17  0.237748  0.034058  0.450044  0.113343   first    first
14  0.898123  0.981077  0.385086  0.117124   first    first
1   0.122057  0.845226  0.696506  0.148699  second   second
4   0.905958  0.333877  0.745048  0.767306  second   second
20  0.943673  0.872107  0.491260  0.840621  second   second
7   0.284415  0.429537  0.383899  0.206239  second   second
19  0.719932  0.795728  0.491034  0.356091  second   second
9   0.454392  0.212103  0.256736  0.170178  second   second
16  0.156722  0.652997  0.947282  0.805937  second   second
15  0.363135  0.957774  0.103713  0.536464  second   second
22  0.067217  0.714923  0.171014  0.317878   third    third
21  0.143653  0.628237  0.222645  0.388624   third    third
12  0.248954  0.932197  0.245250  0.600394   third    third
23  0.971530  0.416940  0.511548  0.683686   third    third
8   0.768713  0.760318  0.970650  0.321685   third    third
3   0.906006  0.350190  0.126388  0.678321   third    third
2   0.726453  0.218114  0.960755  0.198306   third    third
13  0.633827  0.527758  0.400908  0.174506   third    third
10  0.398442  0.394336  0.797771  0.388758  fourth   fourth
5   0.740672  0.245764  0.122640  0.705787  fourth   fourth
24  0.591342  0.783401  0.284444  0.975851  fourth   fourth

In [7]:
d.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25 entries, 0 to 24
Data columns (total 6 columns):
0           25 non-null float64
1           25 non-null float64
2           25 non-null float64
3           25 non-null float64
cat         25 non-null object
cat_sort    25 non-null category
dtypes: category(1), float64(4), object(1)
memory usage: 1.2+ KB