# Medicaid Data by State from CMS (1997-2014)

In an attempt to develop a proxy for Medicaid program generosity (see **`mcaid_by_state`**), it became clear that NIPA data conflicted with other sources.  Specifically, some states had wildly different data from the information presented by [KFF](http://kff.org/medicaid/state-indicator/total-medicaid-spending/#), which is based on Form CM-64 data reported by states to CMS.  To some extent, we have limited recourse.  Before 1997, we NIPA is the only consolidate source of Medicaid spending by state.  However, CMS has made data available from 1997 on.

In this Notebook, we will liberate the data between 1997 and 2014 from the sadistic shackles that CMS has chosen to store it, otherwise known as Excel.

In [1]:
#Data Management
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
from openpyxl import *

#Visualization
import seaborn as sb

%pylab inline

plt.rcParams['axes.edgecolor']='k'
plt.rcParams['axes.linewidth']=1
plt.rcParams['axes.facecolor']=(1,1,1,0)
plt.rcParams['grid.color']='k'
plt.rcParams['grid.linestyle']=':'
plt.rcParams['grid.linewidth']=0.3

Populating the interactive namespace from numpy and matplotlib

C:\Users\marvinw\AppData\Local\Continuum\Anaconda\lib\site-packages\matplotlib\__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))

The [data in question](https://www.medicaid.gov/medicaid-chip-program-information/by-topics/financing-and-reimbursement/expenditure-reports-mbes-cbes.html) are housed in four workbooks with irregular temporal coverage and formatting.  The formatting in particular means we will not be able to rely on a general function to handle all of it.  However, we should be fairly consistent within the workbook, so some room for programmatic efficiency is available.

## 1997-2001

We can start by loading the first notebook and grabbing the sheet names.

In [2]:
#Establish data location
data_dir='O:/Analyst/Marvin/Medicaid/'

#Read in data
fmr97=load_workbook(data_dir+'FMR1997through2001.xlsx')

#Create container to hold sheet objects
fmr97_dict={}

#Capture sheet objects
for sheet in fmr97.get_sheet_names():
    fmr97_dict.update({int(sheet[-4:]):fmr97.get_sheet_by_name(sheet)})
    
fmr97_dict[1997]

Once we have a sheet, we can query its contents in a couple ways...

In [3]:
print fmr97_dict[1998]['A1'].value
print fmr97_dict[1998].cell(row=1,column=1).value

Medicaid Finanacial Management Report
Medicaid Finanacial Management Report

Visual inspection suggests that there are a few pieces of information we want to collect.

1. The state name;
2. Total Medicaid expenditure;
3. The federal share of Medicaid expenditure; and,
4. The state share of Medicaid expenditure.

Each observation in our final set will carry these pieces of information, in addition to the year (which is constant within sheet).  Total expenditure (and the shares) must be aggregated over two data within-state data points:

1. `Total Net Expenditures`
2. `C-Total Net`

To allocate these expenditures, we will rely on position.  The values of net expenditures that follow Alaska, but precede Alabama (presumably ordered by postal code) will be allocated to Alaska.  Therefore, we need a function that will identify a state name as the start of an observation, capture the cumulative expenditures as we move down through the rows, and then simultaneously close out that observation while opening a new observation upon encountering the next state name.

The `cell()` method enables us to iteratively run across the sheet via simple loops.  We can capture the start position of each observation, and then the positions of the relevant values for that observation.  Capturing the rows with the data is easy, because the tags don't change.  The states, on the other hand, are not marked by some common concept ID.  We need to test membership in a list of state names to identify them.  Let's grab that state info first...

In [4]:
#Read in mapping
st_map=pd.read_csv('https://raw.githubusercontent.com/jasonong/List-of-US-States/master/states.csv')

#Convert to dict
st_dict=dict(zip(st_map['State'],st_map['Abbreviation']))

#Include DC
st_dict.update({'District of Columbia':'DC',
                'Dist. Of Col.':'DC',
                'DC':'DC'})

...and now we can define functions to capture state positions, state data, and a consolidated view of all relevant state data in a given sheet.

In [75]:
def get_state_pos_list(sheet,st_dict=st_dict):
    '''Function captures state positions in a given sheet of an active workbook'''
    #Create a container for state positions
    state_pos=[]
    #For each row...
    for i in range(int(sheet.max_row)):
        #...if the cell value is in the list of states...
        if sheet.cell(row=i+1,column=1).value in st_dict.keys():
            #...capture the position and the cell value
            state_pos.append((i+1,sheet.cell(row=i+1,column=1).value))
    return state_pos

def scan_col(sheet,col_num,val,row_0=1):
    '''Functions scans a given column for a value and returns the row location'''
    #Initialize row iterator
    row_i=row_0
    #Until we have encountered the value in the given column...
    while sheet.cell(row=row_i,column=col_num).value!=val and row_i<20000:
        #...move down the given column (via iteration)...
        row_i+=1
        #...if we do encounter the value...
        if sheet.cell(row=row_i,column=col_num).value==val:
            return row_i
        
def scan_row(sheet,row_num,val,col_0=1):
    '''Functions scans a given row for a value and returns the column location'''
    #Initialize column iterator
    col_i=col_0
    #Until we have encountered the value in the given column...
    while sheet.cell(row=row_num,column=col_i).value!=val and col_i<20000:
        #...move right across the given row (via iteration)...
        col_i+=1
        #...if we do encounter the value...
        if sheet.cell(row=row_num,column=col_i).value==val:
            return col_i

def get_data_columns(sheet,dlabs=['Total Computable','Federal Share','State Share']):
    '''Function returns dict with the locations of columns containing total, federal share, and state share data'''
    #Identify the first row with data labels
    lab_row=scan_col(sheet,1,'Service Category')
    #Create dict to hold column locations
    dcol1={}
    dcol2={}
    #For each label...
    for lab in dlabs:
        #...capture the column locations in the first bank...
        dcol1.update({lab:scan_row(sheet,lab_row,lab)})
    #Identify the right-most column
    new_start_col=max(np.array([dcol1[lab] for lab in dcol1.keys()]))+1
    #For each label...
    for lab in dlabs:
        #...capture the column locations in the second bank...
        dcol2.update({lab:scan_row(sheet,lab_row,lab,col_0=new_start_col)})
    return (dcol1,dcol2)

def get_data_rows(pos,sheet,exp_components,dcol_dict):
    '''Function returns dicts with the row locations for within state data'''
    #Identify label columns
    lab_row=scan_col(sheet,1,'Service Category')
    col1=1
    col2=scan_row(sheet,lab_row,'Service Category',col_0=col1+1)
    #Create dicts to hold row positions for the current state
    drow1={}
    drow2={}
    #For each component in the first bank...
    for component in exp_components[0]:
        #...capture the row position of that component
        drow1.update({component:scan_col(sheet,col1,component,row_0=pos[0])})
    #For each component in the second bank...
    for component in exp_components[1]:
        #...capture the row position of that component
        drow2.update({component:scan_col(sheet,col2,component,row_0=pos[0])})
    return (drow1,drow2)

def get_state_data(pos,sheet,exp_components,dlabs=['Total Computable','Federal Share','State Share']):
    '''Function returns DF containing the data for a single state in the current year'''
    #Capture the data column locations
    dcols=get_data_columns(sheet)
    #Capture the data row locations
    drows=get_data_rows(pos,sheet,exp_components,dcols)
    print dcols
    print drows
    #Create container to hold bank-specific DFs
    bank_dfs=[]
    #For each bank...
    for bank_i in [1,2]:
        #...create containers to hold component-specific subsets within bank...
        bank_subs=[]
        #...for each component...
        for component in exp_components[bank_i]:
            #...create a dict to hold the data...
            comp_dict={}
            #...for each label...
            for label in dlabs:
                #...capture the data...
                comp_dict.update({label:sheet.cell(row=drows[bank_i][component],
                                                   column=dcols[bank_i][label]).value})
            #...with the component data complete, convert to DF...
            comp_df=DataFrame(comp_dict,index=[component])
            #...and throw it in bank_subs...
            bank_subs.append(comp_df)
        #...with all the component subsets in this bank in hand, concatenate...
        bank_sub_df=pd.concat(bank_subs)
        #...and throw it in bank_dfs...
        bank_dfs.append(bank_sub_df)
    #...concatenate both bank subset together
    state_df=pd.concat(bank_dfs)
    #Integrate the state name
    state_df['state']=pos[1]
    return state_df
    
    
# def get_state_data(pos,sheet,exp_components,dcol_dict):
#     '''Function captures data associated with a given state (defined by pos)'''
#     #Capture the line number in which the state data block starts
#     pos_i=pos[0]
#     #Create a container to hold data for each state-specific component
#     component_tmp=[]
#     #For each component...
#     for component in exp_components:
#         #...until we have encountered the component label in the data label column...
#         while sheet.cell(row=pos_i,column=1).value!=component and pos_i<20000:
#             #...move down the data label column (via iteration)...
#             pos_i+=1
#             #...if we do encounter the component label...
#             if sheet.cell(row=pos_i,column=1).value==component:
#                 #...capture the total, federal, and state data values in dict...
#                 row_data_tmp={}
#                 for label in dcol_dict.keys():
#                     row_data_tmp.update({label:sheet.cell(row=pos_i,column=dcol_dict[label]).value})
#                 #...convert to DF
#                 row_tmp=DataFrame(row_data_tmp,index=[component])
# #                 row_tmp=DataFrame({'total':sheet.cell(row=pos_i,column=tot_col).value,
# #                                    'fed_shr':sheet.cell(row=pos_i,column=fed_col).value,
# #                                    'st_shr':sheet.cell(row=pos_i,column=st_col).value},index=[component])
#                 #...and throw the DF in component_tmp...
#                 component_tmp.append(row_tmp)
#                 break
#     #Once all component data has been collected, concatenate to a single DF
#     component_df=pd.concat(component_tmp)
#     #Integrate the state name
#     component_df['state']=pos[1]
#     return component_df

def get_sheet_data(yr,sheet,exp_components,dcol_dict,st_dict=st_dict):
    '''Function captures expenditure data for all states in the sheet'''
    #Capture state positions
    state_pos=get_state_pos_list(sheet)
    #Create container to hold data for all states
    state_data=[]
    #For each state...
    for pos in state_pos:
        #...throw state-specific data in state_data
        state_data.append(get_state_data(pos,sheet,exp_components,dcol_dict))
    #Once the data for all states is collected, concatenate it all together        
    state_df=pd.concat(state_data)
    #Integrate the year
    state_df['year']=yr
    #Reset index and rename old index column
    state_df=state_df.reset_index().rename(columns={'index':'component'})
    #Set the index
    state_df.set_index(['year','state','component'],inplace=True)
    #Sort the index
    state_df.sortlevel(0,inplace=True)
    return state_df

Does it work?

In [76]:
#Define expenditure components
exp_components97=(['Total Net Expenditures','C-Total Net'],
                  ['Total Net Expenditures','Total'])

state_pos_tmp=get_state_pos_list(fmr97_dict[1998])
print state_pos_tmp[0][1]
get_state_data(state_pos_tmp[0],fmr97_dict[1998],exp_components97)

Alaska
({'State Share': 4, 'Total Computable': 2, 'Federal Share': 3}, {'State Share': 8, 'Total Computable': 6, 'Federal Share': 7})
({'C-Total Net': 89, 'Total Net Expenditures': 54}, {'Total': 71, 'Total Net Expenditures': 36})

IndexError: tuple index out of range

In [46]:
#Define expenditure components
exp_components97=(['Total Net Expenditures','C-Total Net'],
                  ['Total Net Expenditures','Total'])

#Define data column locations
dcol_97={'Total Computable':2,
         'Federal Share':3,
         'State Share':4}

get_sheet_data(1998,fmr97_dict[1998],exp_components97,dcol_97,st_dict)

                                            Federal Share  State Share  \
year state          component
1998 Alabama        C-Total Net                   2189855       599057
                    Total Net Expenditures     1612326171    711814765
     Alaska         C-Total Net                         0            0
                    Total Net Expenditures      238787815    124133504
     Arizona        C-Total Net                         0            0
                    Total Net Expenditures     1241778897    619270188
     Arkansas       C-Total Net                         0            0
                    Total Net Expenditures     1025895613    380353215
     California     C-Total Net                    781733       405230
                    Total Net Expenditures     9393343861   8938945937
     Colorado       C-Total Net                         0            0
                    Total Net Expenditures      835160724    769282517
     Connecticut    C-Total Net                         0            0
                    Total Net Expenditures     1416466977   1415206783
     Delaware       C-Total Net                         0            0
                    Total Net Expenditures      207937634    206232532
     Dist. Of Col.  C-Total Net                         0            0
                    Total Net Expenditures      555552960    309969414
     Florida        C-Total Net                   4450754      2003357
                    Total Net Expenditures     3547675700   2816629015
     Georgia        C-Total Net                         0            0
                    Total Net Expenditures     2126785792   1360810590
     Hawaii         C-Total Net                         0            0
                    Total Net Expenditures      293029407    292987822
     Idaho          C-Total Net                   1229528       332570
                    Total Net Expenditures      285787249    123970521
     Illinois       C-Total Net                   6081658      3274734
                    Total Net Expenditures     3264185240   3249047678
     Indiana        C-Total Net                         0            0
                    Total Net Expenditures     1584696907    992014888
...                                                   ...          ...
     Oklahoma       C-Total Net                         0            0
                    Total Net Expenditures      948581466    391806159
     Oregon         C-Total Net                         0            0
                    Total Net Expenditures     1051490970    657711584
     Pennsylvania   C-Total Net                         0            0
                    Total Net Expenditures     4543905797   3961745030
     Rhode Island   C-Total Net                         0            0
                    Total Net Expenditures      510241238    449666461
     South Carolina C-Total Net                  25209902      6636860
                    Total Net Expenditures     1593679772    666341667
     South Dakota   C-Total Net                     46829        13650
                    Total Net Expenditures      248350180    107215805
     Tennessee      C-Total Net                         0            0
                    Total Net Expenditures     2521519369   1451809971
     Texas          C-Total Net                   1275400       457482
                    Total Net Expenditures     6102963275   3672236434
     Utah           C-Total Net                         0            0
                    Total Net Expenditures      491962041    184971324
     Vermont        C-Total Net                         0            0
                    Total Net Expenditures      247666302    149679386
     Virginia       C-Total Net                         0            0
                    Total Net Expenditures     1208808080   1134949259
     Washington     C-Total Net                         0            0
                    Total Net Expenditures     1735248446   1580475146
     West Virginia  C-Total Net                      3444          778
                    Total Net Expenditures     1001614278    358189890
     Wisconsin      C-Total Net                         0            0
                    Total Net Expenditures     1624196226   1134284599
     Wyoming        C-Total Net                         0            0
                    Total Net Expenditures      125692729     71746498

                                            Total Computable
year state          component
1998 Alabama        C-Total Net                      2788912
                    Total Net Expenditures        2324140936
     Alaska         C-Total Net                            0
                    Total Net Expenditures         362921319
     Arizona        C-Total Net                            0
                    Total Net Expenditures        1861049085
     Arkansas       C-Total Net                            0
                    Total Net Expenditures        1406248828
     California     C-Total Net                      1186963
                    Total Net Expenditures       18332289798
     Colorado       C-Total Net                            0
                    Total Net Expenditures        1604443241
     Connecticut    C-Total Net                            0
                    Total Net Expenditures        2831673760
     Delaware       C-Total Net                            0
                    Total Net Expenditures         414170166
     Dist. Of Col.  C-Total Net                            0
                    Total Net Expenditures         865522374
     Florida        C-Total Net                      6454111
                    Total Net Expenditures        6364304715
     Georgia        C-Total Net                            0
                    Total Net Expenditures        3487596382
     Hawaii         C-Total Net                            0
                    Total Net Expenditures         586017229
     Idaho          C-Total Net                      1562098
                    Total Net Expenditures         409757770
     Illinois       C-Total Net                      9356392
                    Total Net Expenditures        6513232918
     Indiana        C-Total Net                            0
                    Total Net Expenditures        2576711795
...                                                      ...
     Oklahoma       C-Total Net                            0
                    Total Net Expenditures        1340387625
     Oregon         C-Total Net                            0
                    Total Net Expenditures        1709202554
     Pennsylvania   C-Total Net                            0
                    Total Net Expenditures        8505650827
     Rhode Island   C-Total Net                            0
                    Total Net Expenditures         959907699
     South Carolina C-Total Net                     31846762
                    Total Net Expenditures        2260021439
     South Dakota   C-Total Net                        60479
                    Total Net Expenditures         355565985
     Tennessee      C-Total Net                            0
                    Total Net Expenditures        3973329340
     Texas          C-Total Net                      1732882
                    Total Net Expenditures        9775199709
     Utah           C-Total Net                            0
                    Total Net Expenditures         676933365
     Vermont        C-Total Net                            0
                    Total Net Expenditures         397345688
     Virginia       C-Total Net                            0
                    Total Net Expenditures        2343757339
     Washington     C-Total Net                            0
                    Total Net Expenditures        3315723592
     West Virginia  C-Total Net                         4222
                    Total Net Expenditures        1359804168
     Wisconsin      C-Total Net                            0
                    Total Net Expenditures        2758480825
     Wyoming        C-Total Net                            0
                    Total Net Expenditures         197439227

[102 rows x 3 columns]

It at least appears to do so (and spot checks are consistent).  Let's capture all of the data from the current workbook.

In [54]:
def scan_col(sheet,col_num,val,row_0=1):
    '''Functions scans a given column for a value and returns the row location'''
    #Initialize row iterator
    row_i=row_0
    #Until we have encountered the value in the given column...
    while sheet.cell(row=row_i,column=col_num).value!=val and row_i<20000:
        #...move down the given column (via iteration)...
        row_i+=1
        #...if we do encounter the value...
        if sheet.cell(row=row_i,column=col_num).value==val:
            return row_i
        
def scan_row(sheet,row_num,val,col_0=1):
    '''Functions scans a given row for a value and returns the column location'''
    #Initialize column iterator
    col_i=col_0
    #Until we have encountered the value in the given column...
    while sheet.cell(row=row_num,column=col_i).value!=val and col_i<20000:
        #...move right across the given row (via iteration)...
        col_i+=1
        #...if we do encounter the value...
        if sheet.cell(row=row_num,column=col_i).value==val:
            return col_i

def get_data_columns(sheet,dlabs=['Total Computable','Federal Share','State Share']):
    '''Function returns dict with the locations of columns containing total, federal share, and state share data'''
    #Identify the first row with data labels
    lab_row=scan_col(sheet,1,'Service Category')
    #Create dict to hold column locations
    dcol1={}
    dcol2={}
    #For each label...
    for lab in dlabs:
        #...capture the column locations in the first bank...
        dcol1.update({lab:scan_row(sheet,lab_row,lab)})
    #Identify the right-most column
    new_start_col=max(np.array([dcol1[lab] for lab in dcol1.keys()]))+1
    #For each label...
    for lab in dlabs:
        #...capture the column locations in the second bank...
        dcol2.update({lab:scan_row(sheet,lab_row,lab,col_0=new_start_col)})
    return (dcol1,dcol2)

def get_wb_data(wb_dict,exp_components,st_dict=st_dict):
    '''Function returns Medicaid expenditure by state from all years (sheets) in workbook'''
    #Create container to hold data from each sheet
    wb_list=[]
    #For each year...
    for yr in wb_dict.keys():
        #...identify data columns...
        dcol_dict=get_data_columns(wb_dict[yr])
        #...throw the sheet-specific data in fmr97_list
        wb_list.append(get_sheet_data(yr,wb_dict[yr],exp_components,dcol_dict,st_dict))
    #Concatenate into a single DF
    wb_df=pd.concat(wb_list)
    #Sort index
    wb_df.sortlevel(0,inplace=True)
    return wb_df

#Capture data for 1997-2001
fmr97_full=get_wb_data(fmr97_dict,exp_components97,dcol_97)

#Sum over components
fmr97_df=fmr97_full.groupby(level=['year','state']).sum()

fmr97_df

                     Federal Share  State Share  Total Computable
year state
1997 Alabama            1528097087    667262659        2195359746
     Alaska              202497708    157616505         360114213
     Arizona            1174110456    584523435        1758633891
     Arkansas            963246020    350302642        1313548662
     California         8647331500   8565120199       17212451699
     Colorado            792847741    720156677        1513004418
     Connecticut        1356990803   1355461186        2712451989
     Delaware            204439680    202139284         406578964
     Dist. Of Col.       420281837    419316130         839597967
     Florida            3503058701   2767048868        6270107569
     Georgia            2160052070   1340385675        3500437745
     Hawaii              279424601    279341983         558766584
     Idaho               277111277    130034312         407145589
     Illinois           3297041457   3284228889        6581270346
     Indiana            1529183469    949321859        2478505328
     Iowa                756759308    443877969        1200637277
     Kansas              599415178    416760939        1016176117
     Kentucky           1783473012    761378700        2544851712
     Louisiana          2400089769    630866458        3030956227
     Maine               670782673    380204995        1050987668
     Maryland           1350201604   1337965586        2688167190
     Massachusetts      2476204700   2465235742        4941440442
     Michigan           3105631393   2507267154        5612898547
     Minnesota          1442369626   1240619296        2682988922
     Mississippi        1303394509    382902026        1686296535
     Missouri           1869105980   1242021691        3111127671
     Montana             265233850    111940508         377174358
     Nebraska            444989528    304621301         749610829
     Nevada              238856815    234698009         473554824
     New Hampshire       361181221    359408437         720589658
...                            ...          ...               ...
2001 Massachusetts      3368354771   3310310980        6678665751
     Michigan           4081157059   3167139206        7248296265
     Minnesota          1972552540   1863318039        3835870579
     Mississippi        1884881153    565371657        2450252810
     Missouri           2964514311   1850465571        4814979882
     Montana             356825032    125532372         482357404
     Nebraska            727135755    471624344        1198760099
     Nevada              342057527    332280361         674337888
     New Hampshire       437383870    436024239         873408109
     New Jersey         3599518957   3563154184        7162673141
     New Mexico         1104060777    373007203        1477067980
     New York          15730477767  15644923772       31375401539
     North Carolina     3850734835   2299946752        6150681587
     North Dakota        286976134    119550880         406527014
     Ohio               5082395473   3489253389        8571648862
     Oklahoma           1490757710    561009874        2051767584
     Oregon             1604259817   1054098574        2658358391
     Pennsylvania       5891468994   5016874152       10908343146
     Rhode Island        650170674    552956204        1203126878
     South Carolina     2177263829    897192161        3074455990
     South Dakota        331070165    138664334         469734499
     Tennessee          3528514477   1990859237        5519373714
     Texas              7050331820   4554307793       11604639613
     Utah                596531223    237188892         833720115
     Vermont             376401404    225065689         601467093
     Virginia           1609651633   1427194754        3036846387
     Washington         2191887138   2113837109        4305724247
     West Virginia      1167100614    381516287        1548616901
     Wisconsin          2390580291   1623540001        4014120292
     Wyoming             158683221     84725706         243408927

[255 rows x 3 columns]

## 2002-2011

Let's move on to the next workbook, and capture the sheets.

In [24]:
#Read in data
fmr02=load_workbook(data_dir+'NetExpenditure02through11.xlsx')

#Create container to hold sheet objects
fmr02_dict={}

#Capture sheet objects
for sheet in fmr02.get_sheet_names():
    fmr02_dict.update({int(sheet[-4:]):fmr02.get_sheet_by_name(sheet)})
    
fmr02_dict

{2002: <Worksheet "2002">,
 2003: <Worksheet "2003">,
 2004: <Worksheet "2004">,
 2005: <Worksheet "2005">,
 2006: <Worksheet "2006">,
 2007: <Worksheet "2007">,
 2008: <Worksheet "2008">,
 2009: <Worksheet "2009">,
 2010: <Worksheet "2010">,
 2011: <Worksheet "2011">}

A wrinkle has arisen with this batch of sheets.  The columns holding the total, federal share, and state share data values are inconsistent.  The first implication was a need to go back and retrofit our earlier functions to allow for variation in the data column locations.  The second is a need to now define a function that can locate which columns hold the data (also done retroactively).

In [58]:
#Define list of components
exp_components02=['Total Net Expenditures','C-Total Net','T-Total Net Expenditures']

#Capture data for 2002-2011
fmr02_full=get_wb_data(fmr02_dict,exp_components02)

#Sum over components
fmr02_df=fmr02_full.groupby(level=['year','state']).sum()

fmr02_df

                     Federal Share  State Share  Total Computable
year state
2002 Alabama            2188351619    909547801        3097899420
     Alaska              460370736    252750498         713121234
     Arizona            2376800704   1164798017        3541598721
     Arkansas           1631673098    607972886        2239645984
     California        13967040787  12964521340       26931562127
     Colorado           1167103950   1155964749        2323068699
     Connecticut        1744286455   1715499119        3459785574
     Delaware            318201242    315845109         634046351
     Dist. Of Col.       720647650    307394119        1028041769
     Florida            5631499166   4305148514        9936647680
     Georgia            3684679643   2556531811        6241211454
     Hawaii              421279361    324324538         745603899
     Idaho               563987947    226318839         790306786
     Illinois           4448545560   4397820017        8846365577
     Indiana            2813665541   1700687665        4514353206
     Iowa               1632554511    958869227        2591423738
     Kansas             1106549919    730167277        1836717196
     Kentucky           2682138350   1141327344        3823465694
     Louisiana          3503455629   1461000947        4964456576
     Maine               965982366    479750187        1445732553
     Maryland           1927846222   1851782796        3779629018
     Massachusetts      4091717716   4043468895        8135186611
     Michigan           4285784545   3301908909        7587693454
     Minnesota          2218189889   2196371844        4414561733
     Mississippi        2195750066    686560269        2882310335
     Missouri           3341118516   2102741219        5443859735
     Montana             421899200    149557255         571456455
     Nebraska            811585701    543574586        1355160287
     Nevada              407107914    401090430         808198344
     New Hampshire       509092323    507279227        1016371550
...                            ...          ...               ...
2011 Massachusetts      7563049178   5681760089       13244809267
     Michigan           8609448391   3466196740       12075645131
     Minnesota          4673082907   3598242914        8271325821
     Mississippi        3547384811    863457297        4410842108
     Missouri           5613276573   2497155842        8110432415
     Montana             721218683    248355776         969574459
     Nebraska           1088550834    602894685        1691445519
     Nevada              921400323    642830112        1564230435
     New Hampshire       764329261    584448219        1348777480
     New Jersey         5972607395   4692948183       10665555578
     New Mexico         2608857166    781632598        3390489764
     New York          29606678721  22270740572       51877419293
     North Carolina     7300629278   3058887644       10359516922
     North Dakota        470917336    240943349         711860685
     Ohio              11020801159   4860486519       15881287678
     Oklahoma           3000572178   1122973661        4123545839
     Oregon             3022551991   1363770942        4386322933
     Pennsylvania      12679823753   7715190970       20395014723
     Rhode Island       1260756500    859752186        2120508686
     South Carolina     3783184307   1259006806        5042191113
     South Dakota        535576962    232645770         768222732
     Tennessee          5733258579   2290869347        8024127926
     Texas             18527627165   9348658967       27876286132
     Utah               1329636015    403665852        1733301867
     Vermont             836687120    445195963        1281883083
     Virginia           4000670761   3012960981        7013631742
     Washington         4263172003   3084064595        7347236598
     West Virginia      2154459093    585762516        2740221609
     Wisconsin          4581284692   2352774672        6934059364
     Wyoming             303822368    223339403         527161771

[510 rows x 3 columns]

In [60]:
fmr02_full.ix[2003]

                                        Federal Share  State Share  \
state         component
Alabama       C-Total Net                      119547        30954
              T-Total Net Expenditures              0            0
              Total Net Expenditures       2508235419    969597512
Alaska        C-Total Net                    22040388      9094345
              T-Total Net Expenditures              0            0
              Total Net Expenditures        546694848    282883575
Arizona       C-Total Net                           0            0
              T-Total Net Expenditures              0            0
              Total Net Expenditures       2999892209   1219306194
Arkansas      C-Total Net                    29890773      7012529
              T-Total Net Expenditures              0            0
              Total Net Expenditures       1769349220    560244380
California    C-Total Net                    34541633     18599762
              T-Total Net Expenditures              0            0
              Total Net Expenditures      15768565921  14328488355
Colorado      C-Total Net                           0            0
              T-Total Net Expenditures              0            0
              Total Net Expenditures       1317486269   1234673591
Connecticut   C-Total Net                       31774        17109
              T-Total Net Expenditures              0            0
              Total Net Expenditures       1826504040   1680079906
Delaware      C-Total Net                      161574        86998
              T-Total Net Expenditures              0            0
              Total Net Expenditures        372510520    345959751
Dist. Of Col. C-Total Net                     5924460      1574854
              T-Total Net Expenditures              0            0
              Total Net Expenditures        769212310    306924668
Florida       C-Total Net                    58343288     23622551
              T-Total Net Expenditures              0            0
              Total Net Expenditures       6603449252   4322079460
...                                               ...          ...
South Dakota  C-Total Net                     6272531      2017386
              T-Total Net Expenditures              0            0
              Total Net Expenditures        376307571    159888323
Tennessee     C-Total Net                           0            0
              T-Total Net Expenditures              0            0
              Total Net Expenditures       4211212123   2145950940
Texas         C-Total Net                      325866       126523
              T-Total Net Expenditures         104894      -104894
              Total Net Expenditures       9490054841   5929971855
Utah          C-Total Net                           0            0
              T-Total Net Expenditures         104894      -104894
              Total Net Expenditures        796806768    295712431
Vermont       C-Total Net                           0            0
              T-Total Net Expenditures         104894      -104894
              Total Net Expenditures        453385626    251643062
Virginia      C-Total Net                    14168372      7505748
              T-Total Net Expenditures         104894      -104894
              Total Net Expenditures       1855782421   1669067393
Washington    C-Total Net                           0            0
              T-Total Net Expenditures        2439225     -2439225
              Total Net Expenditures       2641403102   2350665295
West Virginia C-Total Net                           0            0
              T-Total Net Expenditures        2723648     -2723648
              Total Net Expenditures       1424820633    432927294
Wisconsin     C-Total Net                    23664150      9713400
              T-Total Net Expenditures              0            0
              Total Net Expenditures       2881290864   1907761370
Wyoming       C-Total Net                           0            0
              T-Total Net Expenditures        2723648     -2723648
              Total Net Expenditures        214619085    122665313

                                        Total Computable
state         component
Alabama       C-Total Net                         150501
              T-Total Net Expenditures                 0
              Total Net Expenditures          3477832931
Alaska        C-Total Net                       31134733
              T-Total Net Expenditures                 0
              Total Net Expenditures           829578423
Arizona       C-Total Net                              0
              T-Total Net Expenditures                 0
              Total Net Expenditures          4219198403
Arkansas      C-Total Net                       36903302
              T-Total Net Expenditures                 0
              Total Net Expenditures          2329593600
California    C-Total Net                       53141395
              T-Total Net Expenditures                 0
              Total Net Expenditures         30097054276
Colorado      C-Total Net                              0
              T-Total Net Expenditures                 0
              Total Net Expenditures          2552159860
Connecticut   C-Total Net                          48883
              T-Total Net Expenditures                 0
              Total Net Expenditures          3506583946
Delaware      C-Total Net                         248572
              T-Total Net Expenditures                 0
              Total Net Expenditures           718470271
Dist. Of Col. C-Total Net                        7499314
              T-Total Net Expenditures                 0
              Total Net Expenditures          1076136978
Florida       C-Total Net                       81965839
              T-Total Net Expenditures                 0
              Total Net Expenditures         10925528712
...                                                  ...
South Dakota  C-Total Net                        8289917
              T-Total Net Expenditures                 0
              Total Net Expenditures           536195894
Tennessee     C-Total Net                              0
              T-Total Net Expenditures                 0
              Total Net Expenditures          6357163063
Texas         C-Total Net                         452389
              T-Total Net Expenditures                 0
              Total Net Expenditures         15420026696
Utah          C-Total Net                              0
              T-Total Net Expenditures                 0
              Total Net Expenditures          1092519199
Vermont       C-Total Net                              0
              T-Total Net Expenditures                 0
              Total Net Expenditures           705028688
Virginia      C-Total Net                       21674120
              T-Total Net Expenditures                 0
              Total Net Expenditures          3524849814
Washington    C-Total Net                              0
              T-Total Net Expenditures                 0
              Total Net Expenditures          4992068397
West Virginia C-Total Net                              0
              T-Total Net Expenditures                 0
              Total Net Expenditures          1857747927
Wisconsin     C-Total Net                       33377550
              T-Total Net Expenditures                 0
              Total Net Expenditures          4789052234
Wyoming       C-Total Net                              0
              T-Total Net Expenditures                 0
              Total Net Expenditures           337284398

[153 rows x 3 columns]

In [ ]:
print fmr97_dict[1998].cell(row=1,column=1).value
print fmr97_dict[1998].max_row
print type(fmr97_dict[1998].max_row)
print type(int(fmr97_dict[1998].max_row))
for i in range(int(fmr97_dict[1998].max_row)):
    print (i+1,fmr97_dict[1998].cell(row=i+1,column=1).value)

In [ ]:
dir(fmr97_dict[1998])

In [ ]:
dir(fmr97)